### PR TITLE
enable compile for all platforms

### PR DESCRIPTION
**Pull request by kennethlimcp**
- moved #include to .h file
- use PARTICLE flag instead of PHOTON
- bump version to 1.0.1

You will need to reimport this library in the Web IDE to update the changes :)

Thanks!

### CODE REVIEW

**Comment by kennethlimcp** [comment]
ping @tripzero

**Comment by kennethlimcp** [comment]
ping @tripzero

**Comment by tripzero** [comment]
@kennethlimcp sorry about the wait.  merged now.

**Comment by tripzero** [comment]
new version re-imported.

**Pull request merged**
